#!/usr/bin/env python3
"""
Fetch Daily Orderbook Snapshots for Active Markets (Native APIs)

Fetches current orderbook snapshots for all active political markets
with sufficient volume, and accumulates them over time for liquidity analysis.

Each daily run appends one snapshot per market to the existing history.
Downstream scripts (calculate_liquidity_metrics.py) aggregate these
snapshots into spread/depth statistics.

Market source: active_markets.json (generated by generate_web_data.py)
Output:
    data/orderbook_history_polymarket.json
    data/orderbook_history_kalshi.json
"""

import requests
import time
import os
import sys
import threading

try:
    import orjson
    def _load_json(f):
        return orjson.loads(f.read())
    def _dump_json(obj):
        return orjson.dumps(obj)
except ImportError:
    import json
    def _load_json(f):
        return json.load(f)
    def _dump_json(obj):
        return json.dumps(obj).encode()
from datetime import datetime
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

# Paths
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import BASE_DIR, DATA_DIR

def _atomic_write_json(path, data):
    """Write JSON atomically, using orjson if available for speed."""
    import tempfile
    path = Path(path)
    fd, tmp = tempfile.mkstemp(dir=path.parent, suffix='.tmp')
    try:
        with os.fdopen(fd, 'wb') as f:
            f.write(_dump_json(data))
        os.replace(tmp, path)
    except:
        os.unlink(tmp)
        raise

ACTIVE_MARKETS_FILE = BASE_DIR / "docs" / "data" / "active_markets.json"
PM_OUTPUT_FILE = DATA_DIR / "orderbook_history_polymarket.json"
KALSHI_OUTPUT_FILE = DATA_DIR / "orderbook_history_kalshi.json"
OLD_CHECKPOINT_FILE = DATA_DIR / "orderbook_fetch_checkpoint.json"

# Native API endpoints
PM_CLOB_BOOK_URL = "https://clob.polymarket.com/book"
KALSHI_API_BASE = "https://api.elections.kalshi.com/trade-api/v2"

# Parallelism settings
NUM_WORKERS = 10
MAX_RETRIES = 3
RETRY_DELAY = 5

# Market filtering
MIN_VOLUME = 1000  # Only fetch markets with >= $1,000 volume

# Thread-safe state
_lock = threading.Lock()


def log(msg):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


class RateLimiter:
    """Thread-safe rate limiter."""
    def __init__(self, delay):
        self._delay = delay
        self._lock = threading.Lock()
        self._last = 0.0

    def wait(self):
        with self._lock:
            now = time.monotonic()
            elapsed = now - self._last
            if elapsed < self._delay:
                time.sleep(self._delay - elapsed)
            self._last = time.monotonic()


_rate_limiter = RateLimiter(0.12)  # ~80 req/sec across all workers


def fetch_pm_orderbook(token_id):
    """Fetch current orderbook from Polymarket CLOB API."""
    for attempt in range(MAX_RETRIES):
        try:
            _rate_limiter.wait()
            response = requests.get(
                PM_CLOB_BOOK_URL,
                params={'token_id': token_id},
                timeout=10
            )

            if response.status_code == 200:
                data = response.json()
                if data.get('bids') or data.get('asks'):
                    return data
                return {}
            elif response.status_code == 429:
                time.sleep(10 * (2 ** attempt))
                continue
            elif response.status_code == 404:
                return {}
            else:
                return None

        except Exception:
            if attempt < MAX_RETRIES - 1:
                time.sleep(RETRY_DELAY)
                continue
            return None

    return None


def fetch_kalshi_orderbook(ticker):
    """Fetch current orderbook from Kalshi native API."""
    for attempt in range(MAX_RETRIES):
        try:
            _rate_limiter.wait()
            response = requests.get(
                f"{KALSHI_API_BASE}/markets/{ticker}/orderbook",
                timeout=10
            )

            if response.status_code == 200:
                data = response.json()
                if data.get('orderbook'):
                    return data
                return {}
            elif response.status_code == 429:
                time.sleep(10 * (2 ** attempt))
                continue
            elif response.status_code == 404:
                return {}
            else:
                return None

        except Exception:
            if attempt < MAX_RETRIES - 1:
                time.sleep(RETRY_DELAY)
                continue
            return None

    return None


def extract_metrics_from_snapshot(snapshot, platform='polymarket'):
    """Extract key metrics from an orderbook snapshot."""
    timestamp = int(datetime.now().timestamp() * 1000)  # Current time in ms

    if platform == 'kalshi':
        orderbook = snapshot.get('orderbook', {})
        yes_bids = orderbook.get('yes', [])
        no_bids = orderbook.get('no', [])

        if yes_bids:
            best_bid = max(y[0] for y in yes_bids) / 100.0
            bid_depth = sum(y[1] for y in yes_bids)
            best_bid_size = next((y[1] for y in yes_bids if y[0] == max(y[0] for y in yes_bids)), 0)
        else:
            best_bid = None
            bid_depth = 0
            best_bid_size = 0

        if no_bids:
            best_no_bid = max(n[0] for n in no_bids)
            best_ask = 1.0 - (best_no_bid / 100.0)
            ask_depth = sum(n[1] for n in no_bids)
            best_ask_size = next((n[1] for n in no_bids if n[0] == best_no_bid), 0)
        else:
            best_ask = None
            ask_depth = 0
            best_ask_size = 0

        n_bid_levels = len(yes_bids)
        n_ask_levels = len(no_bids)

    else:
        bids = snapshot.get('bids', [])
        asks = snapshot.get('asks', [])

        if bids:
            bid_prices = [(float(b['price']), float(b['size'])) for b in bids]
            best_bid_price, best_bid_size = max(bid_prices, key=lambda x: x[0])
            best_bid = best_bid_price
            bid_depth = sum(p[1] for p in bid_prices)
        else:
            best_bid = None
            best_bid_size = 0
            bid_depth = 0

        if asks:
            ask_prices = [(float(a['price']), float(a['size'])) for a in asks]
            best_ask_price, best_ask_size = min(ask_prices, key=lambda x: x[0])
            best_ask = best_ask_price
            ask_depth = sum(p[1] for p in ask_prices)
        else:
            best_ask = None
            best_ask_size = 0
            ask_depth = 0

        n_bid_levels = len(bids)
        n_ask_levels = len(asks)

    if best_bid is not None and best_ask is not None:
        spread = best_ask - best_bid
        midpoint = (best_ask + best_bid) / 2
        relative_spread = spread / midpoint if midpoint > 0 else None
    else:
        spread = None
        midpoint = None
        relative_spread = None

    total_depth = bid_depth + ask_depth

    return {
        'timestamp': timestamp,
        'best_bid': best_bid,
        'best_ask': best_ask,
        'spread': spread,
        'midpoint': midpoint,
        'relative_spread': relative_spread,
        'bid_depth': bid_depth,
        'ask_depth': ask_depth,
        'total_depth': total_depth,
        'best_bid_size': best_bid_size,
        'best_ask_size': best_ask_size,
        'n_bid_levels': n_bid_levels,
        'n_ask_levels': n_ask_levels
    }


def load_active_markets():
    """Load active markets from active_markets.json, split by platform."""
    if not ACTIVE_MARKETS_FILE.exists():
        log(f"ERROR: {ACTIVE_MARKETS_FILE} not found. Run generate_web_data.py first.")
        return [], []

    import json
    with open(ACTIVE_MARKETS_FILE) as f:
        data = json.load(f)

    markets = data.get('markets', [])
    pm_markets = []
    kalshi_markets = []

    for m in markets:
        volume = m.get('pm_volume', 0) or 0
        k_volume = m.get('k_volume', 0) or 0
        total_volume = volume + k_volume

        if total_volume < MIN_VOLUME:
            continue

        # Polymarket side
        pm_token = m.get('pm_token_id')
        pm_market_id = m.get('pm_market_id')
        if pm_token and pm_market_id:
            pm_markets.append({
                'market_id': pm_market_id,
                'token_id': pm_token,
                'question': (m.get('pm_question') or m.get('label', ''))[:100],
                'category': m.get('category', ''),
                'volume_usd': volume,
            })

        # Kalshi side
        k_ticker = m.get('k_ticker')
        if k_ticker:
            kalshi_markets.append({
                'market_id': k_ticker,
                'ticker': k_ticker,
                'question': (m.get('k_question') or m.get('label', ''))[:100],
                'category': m.get('category', ''),
                'volume_usd': k_volume,
            })

    return pm_markets, kalshi_markets


def fetch_and_accumulate_pm(market_info, existing_data):
    """Fetch PM orderbook and return (market_id, metrics_or_None)."""
    token_id = market_info['token_id']
    snapshot = fetch_pm_orderbook(token_id)
    if snapshot and snapshot != {}:
        metrics = extract_metrics_from_snapshot(snapshot, platform='polymarket')
        return market_info['market_id'], market_info, metrics
    return market_info['market_id'], market_info, None


def fetch_and_accumulate_kalshi(market_info, existing_data):
    """Fetch Kalshi orderbook and return (market_id, metrics_or_None)."""
    ticker = market_info['ticker']
    snapshot = fetch_kalshi_orderbook(ticker)
    if snapshot and snapshot != {}:
        metrics = extract_metrics_from_snapshot(snapshot, platform='kalshi')
        return market_info['market_id'], market_info, metrics
    return market_info['market_id'], market_info, None


def accumulate_snapshot(data_dict, market_id, market_info, metrics, id_field='token_id'):
    """Append a new snapshot to an existing or new market entry."""
    if market_id in data_dict:
        data_dict[market_id]['metrics'].append(metrics)
        data_dict[market_id]['n_snapshots'] = len(data_dict[market_id]['metrics'])
    else:
        data_dict[market_id] = {
            id_field: market_info.get(id_field, market_info.get('market_id', '')),
            'question': market_info.get('question', ''),
            'category': market_info.get('category', ''),
            'volume_usd': market_info.get('volume_usd', 0),
            'trading_close_time': '',
            'n_snapshots': 1,
            'metrics': [metrics]
        }


def main():
    log("=" * 60)
    log("FETCHING ORDERBOOK SNAPSHOTS (ACTIVE MARKETS)")
    log(f"Workers: {NUM_WORKERS}, Min volume: ${MIN_VOLUME:,}")
    log("=" * 60)

    # 1. Load active markets
    log("\n1. Loading active markets...")
    pm_markets, kalshi_markets = load_active_markets()
    log(f"   Polymarket: {len(pm_markets):,} markets (volume >= ${MIN_VOLUME:,})")
    log(f"   Kalshi: {len(kalshi_markets):,} markets (volume >= ${MIN_VOLUME:,})")

    if not pm_markets and not kalshi_markets:
        log("   No markets to fetch. Exiting.")
        return

    # 2. Load existing history
    log("\n2. Loading existing orderbook history...")
    pm_data = {}
    kalshi_data = {}

    if PM_OUTPUT_FILE.exists():
        try:
            with open(PM_OUTPUT_FILE, 'rb') as f:
                pm_data = _load_json(f)
            total_snapshots = sum(m.get('n_snapshots', len(m.get('metrics', []))) for m in pm_data.values())
            log(f"   Polymarket: {len(pm_data):,} markets, {total_snapshots:,} total snapshots")
        except Exception as e:
            log(f"   Warning: Could not load PM history: {e}")

    if KALSHI_OUTPUT_FILE.exists():
        try:
            with open(KALSHI_OUTPUT_FILE, 'rb') as f:
                kalshi_data = _load_json(f)
            total_snapshots = sum(m.get('n_snapshots', len(m.get('metrics', []))) for m in kalshi_data.values())
            log(f"   Kalshi: {len(kalshi_data):,} markets, {total_snapshots:,} total snapshots")
        except Exception as e:
            log(f"   Warning: Could not load Kalshi history: {e}")

    # 3. Fetch Polymarket orderbooks
    log(f"\n3. Fetching {len(pm_markets):,} Polymarket orderbooks...")
    pm_success = 0
    pm_empty = 0

    with ThreadPoolExecutor(max_workers=NUM_WORKERS) as executor:
        futures = {
            executor.submit(fetch_and_accumulate_pm, m, pm_data): m
            for m in pm_markets
        }

        completed = 0
        for future in as_completed(futures):
            market_id, market_info, metrics = future.result()

            with _lock:
                if metrics:
                    accumulate_snapshot(pm_data, market_id, market_info, metrics, id_field='token_id')
                    pm_success += 1
                else:
                    pm_empty += 1

                completed += 1
                if completed % 500 == 0:
                    log(f"   PM progress: {completed}/{len(pm_markets)} "
                        f"({pm_success} with data, {pm_empty} empty)")

    log(f"   Polymarket: {pm_success} with data, {pm_empty} empty")

    # 4. Fetch Kalshi orderbooks
    log(f"\n4. Fetching {len(kalshi_markets):,} Kalshi orderbooks...")
    k_success = 0
    k_empty = 0

    with ThreadPoolExecutor(max_workers=NUM_WORKERS) as executor:
        futures = {
            executor.submit(fetch_and_accumulate_kalshi, m, kalshi_data): m
            for m in kalshi_markets
        }

        completed = 0
        for future in as_completed(futures):
            market_id, market_info, metrics = future.result()

            with _lock:
                if metrics:
                    accumulate_snapshot(kalshi_data, market_id, market_info, metrics, id_field='ticker')
                    k_success += 1
                else:
                    k_empty += 1

                completed += 1
                if completed % 500 == 0:
                    log(f"   Kalshi progress: {completed}/{len(kalshi_markets)} "
                        f"({k_success} with data, {k_empty} empty)")

    log(f"   Kalshi: {k_success} with data, {k_empty} empty")

    # 5. Save results
    log("\n5. Saving results...")
    _atomic_write_json(PM_OUTPUT_FILE, pm_data)
    log(f"   Saved {len(pm_data):,} Polymarket markets")

    _atomic_write_json(KALSHI_OUTPUT_FILE, kalshi_data)
    log(f"   Saved {len(kalshi_data):,} Kalshi markets")

    # Clean up old checkpoint file
    if OLD_CHECKPOINT_FILE.exists():
        OLD_CHECKPOINT_FILE.unlink()
        log("   Removed stale checkpoint file")

    # 6. Summary
    log("\n" + "=" * 60)
    log("SUMMARY")
    log("=" * 60)
    log(f"New snapshots: {pm_success} PM + {k_success} Kalshi = {pm_success + k_success} total")
    log(f"Empty orderbooks: {pm_empty} PM + {k_empty} Kalshi")
    log(f"Total markets in history: {len(pm_data):,} PM + {len(kalshi_data):,} Kalshi")

    if pm_data:
        total = sum(m.get('n_snapshots', len(m.get('metrics', []))) for m in pm_data.values())
        log(f"PM total snapshots: {total:,} (avg {total / len(pm_data):.1f}/market)")

    if kalshi_data:
        total = sum(m.get('n_snapshots', len(m.get('metrics', []))) for m in kalshi_data.values())
        log(f"Kalshi total snapshots: {total:,} (avg {total / len(kalshi_data):.1f}/market)")

    log("\nDone!")


if __name__ == "__main__":
    main()
