#!/usr/bin/env python3
"""
Fetch Daily Orderbook Snapshots for Active Markets (Native APIs)

Fetches current orderbook snapshots for all active political markets
with sufficient volume. Uses incremental summary for fast daily runs.

Flow:
  1. Load orderbook_summary.json (~1 MB) — running stats per market + daily aggregates
  2. Fetch live orderbooks for active markets
  3. Update summary with new snapshots (running stats, daily aggregates)
  4. Save daily raw snapshots to orderbook_snapshots/YYYY-MM-DD.json
  5. Save updated summary

First run requires bootstrap: python bootstrap_orderbook_summary.py

Market source: active_markets.json (generated by generate_web_data.py)
Output:
    data/orderbook_summary.json (primary — drives all downstream scripts)
    data/orderbook_snapshots/YYYY-MM-DD.json (daily raw archive)
"""

import requests
import json
import math
import time
import os
import sys
import threading
import numpy as np
from datetime import datetime, timezone
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

try:
    import orjson
    def _load_json(f):
        return orjson.loads(f.read())
    def _dump_json(obj):
        return orjson.dumps(obj)
except ImportError:
    def _load_json(f):
        return json.load(f)
    def _dump_json(obj):
        return json.dumps(obj).encode()

# Paths
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import BASE_DIR, DATA_DIR

ACTIVE_MARKETS_FILE = BASE_DIR / "docs" / "data" / "active_markets.json"
SUMMARY_FILE = DATA_DIR / "orderbook_summary.json"
SNAPSHOTS_DIR = DATA_DIR / "orderbook_snapshots"

# Native API endpoints
PM_CLOB_BOOK_URL = "https://clob.polymarket.com/book"
KALSHI_API_BASE = "https://api.elections.kalshi.com/trade-api/v2"

# Parallelism settings
NUM_WORKERS = 10
MAX_RETRIES = 3
RETRY_DELAY = 5

# Market filtering
MIN_VOLUME = 1000  # Only fetch markets with >= $1,000 volume

# Thread-safe state
_lock = threading.Lock()


def log(msg):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def safe_val(v):
    """Return value if finite, else None."""
    if v is None:
        return None
    try:
        if math.isfinite(v):
            return v
    except (TypeError, ValueError):
        pass
    return None


class RateLimiter:
    """Thread-safe rate limiter."""
    def __init__(self, delay):
        self._delay = delay
        self._lock = threading.Lock()
        self._last = 0.0

    def wait(self):
        with self._lock:
            now = time.monotonic()
            elapsed = now - self._last
            if elapsed < self._delay:
                time.sleep(self._delay - elapsed)
            self._last = time.monotonic()


_rate_limiter = RateLimiter(0.12)  # ~80 req/sec across all workers


def fetch_pm_orderbook(token_id):
    """Fetch current orderbook from Polymarket CLOB API."""
    for attempt in range(MAX_RETRIES):
        try:
            _rate_limiter.wait()
            response = requests.get(
                PM_CLOB_BOOK_URL,
                params={'token_id': token_id},
                timeout=10
            )

            if response.status_code == 200:
                data = response.json()
                if data.get('bids') or data.get('asks'):
                    return data
                return {}
            elif response.status_code == 429:
                time.sleep(10 * (2 ** attempt))
                continue
            elif response.status_code == 404:
                return {}
            else:
                return None

        except Exception:
            if attempt < MAX_RETRIES - 1:
                time.sleep(RETRY_DELAY)
                continue
            return None

    return None


def fetch_kalshi_orderbook(ticker):
    """Fetch current orderbook from Kalshi native API."""
    for attempt in range(MAX_RETRIES):
        try:
            _rate_limiter.wait()
            response = requests.get(
                f"{KALSHI_API_BASE}/markets/{ticker}/orderbook",
                timeout=10
            )

            if response.status_code == 200:
                data = response.json()
                if data.get('orderbook'):
                    return data
                return {}
            elif response.status_code == 429:
                time.sleep(10 * (2 ** attempt))
                continue
            elif response.status_code == 404:
                return {}
            else:
                return None

        except Exception:
            if attempt < MAX_RETRIES - 1:
                time.sleep(RETRY_DELAY)
                continue
            return None

    return None


def extract_metrics_from_snapshot(snapshot, platform='polymarket'):
    """Extract key metrics from an orderbook snapshot."""
    timestamp = int(datetime.now().timestamp() * 1000)  # Current time in ms

    if platform == 'kalshi':
        orderbook = snapshot.get('orderbook', {})
        yes_bids = orderbook.get('yes', [])
        no_bids = orderbook.get('no', [])

        if yes_bids:
            best_bid = max(y[0] for y in yes_bids) / 100.0
            bid_depth = sum(y[1] for y in yes_bids)
            best_bid_size = next((y[1] for y in yes_bids if y[0] == max(y[0] for y in yes_bids)), 0)
        else:
            best_bid = None
            bid_depth = 0
            best_bid_size = 0

        if no_bids:
            best_no_bid = max(n[0] for n in no_bids)
            best_ask = 1.0 - (best_no_bid / 100.0)
            ask_depth = sum(n[1] for n in no_bids)
            best_ask_size = next((n[1] for n in no_bids if n[0] == best_no_bid), 0)
        else:
            best_ask = None
            ask_depth = 0
            best_ask_size = 0

        n_bid_levels = len(yes_bids)
        n_ask_levels = len(no_bids)

    else:
        bids = snapshot.get('bids', [])
        asks = snapshot.get('asks', [])

        if bids:
            bid_prices = [(float(b['price']), float(b['size'])) for b in bids]
            best_bid_price, best_bid_size = max(bid_prices, key=lambda x: x[0])
            best_bid = best_bid_price
            bid_depth = sum(p[1] for p in bid_prices)
        else:
            best_bid = None
            best_bid_size = 0
            bid_depth = 0

        if asks:
            ask_prices = [(float(a['price']), float(a['size'])) for a in asks]
            best_ask_price, best_ask_size = min(ask_prices, key=lambda x: x[0])
            best_ask = best_ask_price
            ask_depth = sum(p[1] for p in ask_prices)
        else:
            best_ask = None
            best_ask_size = 0
            ask_depth = 0

        n_bid_levels = len(bids)
        n_ask_levels = len(asks)

    if best_bid is not None and best_ask is not None:
        spread = best_ask - best_bid
        midpoint = (best_ask + best_bid) / 2
        relative_spread = spread / midpoint if midpoint > 0 else None
    else:
        spread = None
        midpoint = None
        relative_spread = None

    total_depth = bid_depth + ask_depth

    return {
        'timestamp': timestamp,
        'best_bid': best_bid,
        'best_ask': best_ask,
        'spread': spread,
        'midpoint': midpoint,
        'relative_spread': relative_spread,
        'bid_depth': bid_depth,
        'ask_depth': ask_depth,
        'total_depth': total_depth,
        'best_bid_size': best_bid_size,
        'best_ask_size': best_ask_size,
        'n_bid_levels': n_bid_levels,
        'n_ask_levels': n_ask_levels
    }


def load_active_markets():
    """Load active markets from active_markets.json, split by platform."""
    if not ACTIVE_MARKETS_FILE.exists():
        log(f"ERROR: {ACTIVE_MARKETS_FILE} not found. Run generate_web_data.py first.")
        return [], []

    with open(ACTIVE_MARKETS_FILE) as f:
        data = json.load(f)

    markets = data.get('markets', [])
    pm_markets = []
    kalshi_markets = []

    for m in markets:
        volume = m.get('pm_volume', 0) or 0
        k_volume = m.get('k_volume', 0) or 0
        total_volume = volume + k_volume

        if total_volume < MIN_VOLUME:
            continue

        # Polymarket side
        pm_token = m.get('pm_token_id')
        pm_market_id = m.get('pm_market_id')
        if pm_token and pm_market_id:
            pm_markets.append({
                'market_id': pm_market_id,
                'token_id': pm_token,
                'question': (m.get('pm_question') or m.get('label', ''))[:100],
                'category': m.get('category', ''),
                'volume_usd': volume,
            })

        # Kalshi side
        k_ticker = m.get('k_ticker')
        if k_ticker:
            kalshi_markets.append({
                'market_id': k_ticker,
                'ticker': k_ticker,
                'question': (m.get('k_question') or m.get('label', ''))[:100],
                'category': m.get('category', ''),
                'volume_usd': k_volume,
            })

    return pm_markets, kalshi_markets


def fetch_single(market_info, platform):
    """Fetch orderbook for one market. Returns (market_id, market_info, metrics_or_None)."""
    if platform == 'polymarket':
        snapshot = fetch_pm_orderbook(market_info['token_id'])
    else:
        snapshot = fetch_kalshi_orderbook(market_info['ticker'])

    if snapshot and snapshot != {}:
        metrics = extract_metrics_from_snapshot(snapshot, platform=platform)
        return market_info['market_id'], market_info, metrics
    return market_info['market_id'], market_info, None


def update_running_stat(stat, value):
    """Update running statistics with a new value."""
    if value is None:
        return
    stat["n"] += 1
    stat["sum"] += value
    stat["sum_sq"] += value * value
    if stat["min"] is None or value < stat["min"]:
        stat["min"] = value
    if stat["max"] is None or value > stat["max"]:
        stat["max"] = value


def init_running_stat():
    return {"n": 0, "sum": 0.0, "sum_sq": 0.0, "min": None, "max": None}


def update_summary_market(summary, market_id, market_info, metrics, platform):
    """Update summary with a new snapshot for one market."""
    markets = summary["markets"]

    if market_id not in markets:
        id_field = 'token_id' if platform == 'polymarket' else 'ticker'
        markets[market_id] = {
            "platform": platform,
            "id_value": market_info.get(id_field, market_id),
            "question": market_info.get('question', ''),
            "category": market_info.get('category', ''),
            "volume_usd": market_info.get('volume_usd', 0),
            "n_snapshots": 0,
            "first_timestamp": None,
            "last_timestamp": None,
            "spread": init_running_stat(),
            "rel_spread": init_running_stat(),
            "depth": init_running_stat(),
            "bid_depth": init_running_stat(),
            "ask_depth": init_running_stat(),
            "imbalance": init_running_stat(),
            "midpoint": init_running_stat(),
        }

    entry = markets[market_id]
    entry["n_snapshots"] += 1

    ts = metrics.get('timestamp', 0)
    if ts:
        if entry["first_timestamp"] is None or ts < entry["first_timestamp"]:
            entry["first_timestamp"] = ts
        if entry["last_timestamp"] is None or ts > entry["last_timestamp"]:
            entry["last_timestamp"] = ts

    # Update running stats
    spread = safe_val(metrics.get('spread'))
    update_running_stat(entry["spread"], spread)

    rel_spread = safe_val(metrics.get('relative_spread'))
    update_running_stat(entry["rel_spread"], rel_spread)

    total_depth = safe_val(metrics.get('total_depth'))
    update_running_stat(entry["depth"], total_depth)

    bid_depth = safe_val(metrics.get('bid_depth'))
    update_running_stat(entry["bid_depth"], bid_depth)

    ask_depth = safe_val(metrics.get('ask_depth'))
    update_running_stat(entry["ask_depth"], ask_depth)

    midpoint = safe_val(metrics.get('midpoint'))
    update_running_stat(entry["midpoint"], midpoint)

    if bid_depth is not None and ask_depth is not None and (bid_depth + ask_depth) > 0:
        imb = (bid_depth - ask_depth) / (bid_depth + ask_depth)
        update_running_stat(entry["imbalance"], imb)


def update_summary_daily(summary, today_str, platform, new_metrics_list):
    """Update daily aggregates with today's snapshots."""
    daily = summary.setdefault("daily", {})
    if today_str not in daily:
        daily[today_str] = {}

    spreads = []
    depths = []
    n = 0

    for m in new_metrics_list:
        n += 1
        rs = safe_val(m.get('relative_spread'))
        if rs is not None and rs > 0:
            spreads.append(rs * 100)
        td = safe_val(m.get('total_depth'))
        if td is not None and td > 0:
            depths.append(td)

    entry = {"n_snapshots": n}
    if spreads:
        entry["spread_median"] = round(float(np.median(spreads)), 2)
    if depths:
        entry["depth_median"] = round(float(np.median(depths)), 0)

    daily[today_str][platform] = entry


def main():
    log("=" * 60)
    log("FETCHING ORDERBOOK SNAPSHOTS (ACTIVE MARKETS)")
    log(f"Workers: {NUM_WORKERS}, Min volume: ${MIN_VOLUME:,}")
    log("=" * 60)

    # 1. Load active markets
    log("\n1. Loading active markets...")
    pm_markets, kalshi_markets = load_active_markets()
    log(f"   Polymarket: {len(pm_markets):,} markets (volume >= ${MIN_VOLUME:,})")
    log(f"   Kalshi: {len(kalshi_markets):,} markets (volume >= ${MIN_VOLUME:,})")

    if not pm_markets and not kalshi_markets:
        log("   No markets to fetch. Exiting.")
        return

    # 2. Load existing summary
    log("\n2. Loading orderbook summary...")
    if SUMMARY_FILE.exists():
        with open(SUMMARY_FILE, 'rb') as f:
            summary = _load_json(f)
        n_markets = len(summary.get("markets", {}))
        n_days = len(summary.get("daily", {}))
        log(f"   Loaded summary: {n_markets:,} markets, {n_days} days")
    else:
        log("   No summary found. Starting fresh.")
        log("   (Run bootstrap_orderbook_summary.py first to include historical data)")
        summary = {"version": 1, "markets": {}, "daily": {}}

    today_str = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    # 3. Fetch Polymarket orderbooks
    log(f"\n3. Fetching {len(pm_markets):,} Polymarket orderbooks...")
    pm_success = 0
    pm_empty = 0
    pm_new_metrics = []

    with ThreadPoolExecutor(max_workers=NUM_WORKERS) as executor:
        futures = {
            executor.submit(fetch_single, m, 'polymarket'): m
            for m in pm_markets
        }

        completed = 0
        for future in as_completed(futures):
            market_id, market_info, metrics = future.result()

            with _lock:
                if metrics:
                    update_summary_market(summary, market_id, market_info, metrics, 'polymarket')
                    pm_new_metrics.append(metrics)
                    pm_success += 1
                else:
                    pm_empty += 1

                completed += 1
                if completed % 500 == 0:
                    log(f"   PM progress: {completed}/{len(pm_markets)} "
                        f"({pm_success} with data, {pm_empty} empty)")

    log(f"   Polymarket: {pm_success} with data, {pm_empty} empty")

    # Update daily aggregates for PM
    if pm_new_metrics:
        update_summary_daily(summary, today_str, 'polymarket', pm_new_metrics)

    # 4. Fetch Kalshi orderbooks
    log(f"\n4. Fetching {len(kalshi_markets):,} Kalshi orderbooks...")
    k_success = 0
    k_empty = 0
    k_new_metrics = []

    with ThreadPoolExecutor(max_workers=NUM_WORKERS) as executor:
        futures = {
            executor.submit(fetch_single, m, 'kalshi'): m
            for m in kalshi_markets
        }

        completed = 0
        for future in as_completed(futures):
            market_id, market_info, metrics = future.result()

            with _lock:
                if metrics:
                    update_summary_market(summary, market_id, market_info, metrics, 'kalshi')
                    k_new_metrics.append(metrics)
                    k_success += 1
                else:
                    k_empty += 1

                completed += 1
                if completed % 500 == 0:
                    log(f"   Kalshi progress: {completed}/{len(kalshi_markets)} "
                        f"({k_success} with data, {k_empty} empty)")

    log(f"   Kalshi: {k_success} with data, {k_empty} empty")

    # Update daily aggregates for Kalshi
    if k_new_metrics:
        update_summary_daily(summary, today_str, 'kalshi', k_new_metrics)

    # 5. Save daily raw snapshots (small archive file)
    log("\n5. Saving daily snapshots...")
    SNAPSHOTS_DIR.mkdir(parents=True, exist_ok=True)
    daily_file = SNAPSHOTS_DIR / f"{today_str}.json"

    # Collect all today's raw snapshots with market IDs
    daily_raw = {
        "date": today_str,
        "pm_snapshots": pm_success,
        "k_snapshots": k_success,
        "metrics": pm_new_metrics + k_new_metrics
    }
    with open(daily_file, 'w') as f:
        json.dump(daily_raw, f)
    size_kb = daily_file.stat().st_size / 1024
    log(f"   Saved {daily_file.name} ({size_kb:.0f} KB)")

    # 6. Save updated summary
    log("\n6. Saving updated summary...")
    summary["last_updated"] = datetime.now(timezone.utc).isoformat()

    import tempfile
    fd, tmp = tempfile.mkstemp(dir=SUMMARY_FILE.parent, suffix='.tmp')
    try:
        with os.fdopen(fd, 'wb') as f:
            f.write(_dump_json(summary))
        os.replace(tmp, SUMMARY_FILE)
    except:
        os.unlink(tmp)
        raise

    size_mb = SUMMARY_FILE.stat().st_size / 1024 / 1024
    log(f"   Saved {SUMMARY_FILE.name} ({size_mb:.1f} MB)")

    # 7. Summary
    log("\n" + "=" * 60)
    log("SUMMARY")
    log("=" * 60)
    log(f"New snapshots: {pm_success} PM + {k_success} Kalshi = {pm_success + k_success} total")
    log(f"Empty orderbooks: {pm_empty} PM + {k_empty} Kalshi")
    n_markets = len(summary.get("markets", {}))
    total_snapshots = sum(m.get("n_snapshots", 0) for m in summary["markets"].values())
    log(f"Total in summary: {n_markets:,} markets, {total_snapshots:,} snapshots")
    log(f"Daily history: {len(summary.get('daily', {}))} days")

    log("\nDone!")


if __name__ == "__main__":
    main()
