#!/usr/bin/env python3
"""
Master runner for paper generation.

Usage:
    python scripts/generate_paper.py --cutoff 2025-01-15

Sets BELLWETHER_CUTOFF_DATE and BELLWETHER_OUTPUT_DIR env vars, then runs
all 14 analysis scripts in dependency order. Output goes to papers/{year}/.
"""

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

BASE_DIR = Path("/Users/paschal/Hall Research Dropbox/Elliot Paschal/Polymarket:Kalshi")
SCRIPTS_DIR = BASE_DIR / "scripts"


# ---------------------------------------------------------------------------
# Script execution order
# ---------------------------------------------------------------------------

PHASE_1 = [
    ("create_brier_cohorts.py", "Brier cohort CSVs"),
    ("election_winner_markets_comparison.py", "Election winner comparison"),
]

PHASE_2 = [
    ("table_1_aggregate.py", "Table 1: Aggregate statistics"),
    ("table_2_election_types.py", "Table 2: Election types"),
    ("table_3_platform_comparison.py", "Table 3: Platform comparison"),
    ("table_4_brier_by_election_type.py", "Table 4: Brier by election type"),
    ("table_partisan_bias_regression.py", "Table: Partisan bias regression"),
    ("volume_timeseries_by_category.py", "Figure: Volume timeseries"),
    ("prediction_vs_volume.py", "Figure: Prediction vs volume"),
    ("calibration_density_plots.py", "Figure: Calibration density (all)"),
    ("calibration_density_plots_elections.py", "Figure: Calibration density (elections)"),
    ("brier_score_analysis.py", "Figure: Brier score analysis"),
    ("calibration_by_race_closeness.py", "Figure: Calibration by race closeness"),
    ("partisan_bias_calibration.py", "Figure: Partisan bias calibration"),
]


def run_script(script_name, env, description):
    """Run a single script and return (success, elapsed_seconds, error_msg)."""
    script_path = SCRIPTS_DIR / script_name
    if not script_path.exists():
        return False, 0, f"File not found: {script_path}"

    start = time.time()
    try:
        result = subprocess.run(
            [sys.executable, "-u", str(script_path)],
            env=env,
            capture_output=True,
            text=True,
            timeout=300,
        )
        elapsed = time.time() - start
        if result.returncode != 0:
            error = result.stderr.strip()[-500:] if result.stderr else "Unknown error"
            return False, elapsed, error
        return True, elapsed, None
    except subprocess.TimeoutExpired:
        return False, 300, "Timed out after 5 minutes"
    except Exception as e:
        return False, time.time() - start, str(e)


def compile_latex(tex_file, output_dir):
    """Compile the LaTeX document to PDF (pdflatex only, no pythontex).

    Since all graphs and tables are pre-generated by the scripts above,
    we skip pythontex and just run pdflatex directly.  Two passes handle
    cross-references; bibtex runs in between if a .bib file exists.

    Returns True on success.
    """
    import shutil

    tex_dir = tex_file.parent
    tex_name = tex_file.stem  # "Prediction Markets"

    # pdflatex flags: nonstop mode so it doesn't hang on errors
    pdf_cmd = [
        "pdflatex",
        "-interaction=nonstopmode",
        "-output-directory", str(tex_dir),
        str(tex_file),
    ]

    bib_file = tex_dir / "references.bib"
    bib_cmd = ["bibtex", str(tex_dir / tex_name)] if bib_file.exists() else None

    steps = [("pdflatex (pass 1)", pdf_cmd)]
    if bib_cmd:
        steps.append(("bibtex", bib_cmd))
    steps.append(("pdflatex (pass 2)", pdf_cmd))
    steps.append(("pdflatex (pass 3)", pdf_cmd))

    for step_name, cmd in steps:
        print(f"  {step_name}...", end=" ", flush=True)
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=str(tex_dir),
            timeout=120,
        )
        if result.returncode != 0:
            print("FAILED")
            # Show last few lines of the log for diagnosis
            log_file = tex_dir / f"{tex_name}.log"
            if log_file.exists():
                log_text = log_file.read_text()
                # Find errors in log
                errors = [l for l in log_text.splitlines() if l.startswith("!")]
                if errors:
                    print("  LaTeX errors:")
                    for e in errors[:10]:
                        print(f"    {e}")
            return False
        print("OK")

    # Copy PDF to paper output directory
    built_pdf = tex_dir / f"{tex_name}.pdf"
    dest_pdf = output_dir / f"{tex_name}.pdf"
    if built_pdf.exists():
        shutil.copy2(built_pdf, dest_pdf)
        size_mb = dest_pdf.stat().st_size / (1024 * 1024)
        print(f"\n  PDF: {dest_pdf} ({size_mb:.1f} MB)")
        return True
    else:
        print(f"  WARNING: Expected PDF not found at {built_pdf}")
        return False


def main():
    parser = argparse.ArgumentParser(description="Generate paper figures and tables")
    parser.add_argument("--cutoff", required=True, help="Cutoff date YYYY-MM-DD")
    args = parser.parse_args()

    # Derive output dir from cutoff year
    cutoff_year = args.cutoff[:4]
    output_dir = BASE_DIR / "papers" / cutoff_year
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print(f"GENERATING PAPER: cutoff={args.cutoff}, output={output_dir}")
    print("=" * 70)

    # Set env vars for child scripts
    env = os.environ.copy()
    env["BELLWETHER_CUTOFF_DATE"] = args.cutoff
    env["BELLWETHER_OUTPUT_DIR"] = str(output_dir)

    all_scripts = [("PHASE 1", PHASE_1), ("PHASE 2", PHASE_2)]
    results = []

    for phase_name, scripts in all_scripts:
        print(f"\n{'=' * 70}")
        print(f"{phase_name}")
        print(f"{'=' * 70}")

        for script_name, description in scripts:
            print(f"\n  Running: {description} ({script_name})...")
            success, elapsed, error = run_script(script_name, env, description)
            status = "OK" if success else "FAIL"
            results.append((script_name, description, success, elapsed, error))
            print(f"  [{status}] {elapsed:.1f}s")
            if error:
                print(f"  Error: {error[:200]}")

    # Summary
    print(f"\n{'=' * 70}")
    print("SUMMARY")
    print(f"{'=' * 70}")

    succeeded = sum(1 for r in results if r[2])
    failed = sum(1 for r in results if not r[2])
    total_time = sum(r[3] for r in results)

    for script_name, description, success, elapsed, error in results:
        status = "OK  " if success else "FAIL"
        print(f"  [{status}] {description:<45} ({elapsed:.1f}s)")

    print(f"\n  {succeeded}/{succeeded + failed} scripts succeeded in {total_time:.0f}s")
    print(f"  Output: {output_dir}")

    # Copy output to standard dirs so LaTeX compiles as-is
    import shutil
    std_graphs = BASE_DIR / "graphs" / "combined"
    std_tables = BASE_DIR / "tables"
    paper_graphs = output_dir / "graphs" / "combined"
    paper_tables = output_dir / "tables"

    if paper_graphs.exists():
        for f in paper_graphs.glob("*.png"):
            shutil.copy2(f, std_graphs / f.name)
        print(f"\n  Copied {len(list(paper_graphs.glob('*.png')))} PNGs to {std_graphs}")

    if paper_tables.exists():
        for f in paper_tables.glob("*.tex"):
            shutil.copy2(f, std_tables / f.name)
        print(f"  Copied {len(list(paper_tables.glob('*.tex')))} .tex files to {std_tables}")

    # ------------------------------------------------------------------
    # Compile LaTeX → PDF
    # ------------------------------------------------------------------
    # The .tex file uses pythontex to run scripts inline, but we've
    # already pre-generated all outputs above.  Running pdflatex alone
    # (without pythontex) is sufficient — it picks up the pre-generated
    # graphs/ and tables/ files via \includegraphics and \input.
    # ------------------------------------------------------------------

    tex_file = BASE_DIR / "Prediction Markets.tex"
    if not tex_file.exists():
        print(f"\n  WARNING: {tex_file} not found — skipping PDF compilation")
    elif failed > 0:
        print(f"\n  Skipping PDF compilation ({failed} script(s) failed)")
    else:
        print(f"\n{'=' * 70}")
        print("COMPILING LATEX")
        print(f"{'=' * 70}")

        pdf_ok = compile_latex(tex_file, output_dir)
        if not pdf_ok:
            print("  PDF compilation failed (see errors above)")

    print(f"\n{'=' * 70}")
    print("DONE")
    print(f"{'=' * 70}")
    if failed == 0:
        print(f"  Paper: {output_dir / 'Prediction Markets.pdf'}")
    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
