#!/usr/bin/env python3
"""
Regression test for generate_web_data.py JSON outputs.

Usage:
    python test_web_data_regression.py --snapshot   # Capture baseline before migration
    python test_web_data_regression.py --check      # Compare current outputs against baseline

Exit codes:
    0 = PASS or WARN (safe to proceed)
    1 = FAIL (breaking changes detected)
"""

import argparse
import json
import math
import os
import shutil
import sys
from datetime import datetime
from pathlib import Path

from config import WEBSITE_DIR, DATA_DIR

WEB_DATA_DIR = WEBSITE_DIR / "data"
SNAPSHOT_DIR = DATA_DIR / "test_snapshots" / "web_data_baseline"

# JSON files generated by generate_web_data.py that we test
# Excludes large data files (active_markets.json, market_map.json, etc.) that aren't
# part of the research tab analytics
RESEARCH_TAB_FILES = [
    "summary.json",
    "aggregate_statistics.json",
    "brier_by_category.json",
    "brier_by_election_type.json",
    "brier_by_margin.json",
    "brier_convergence.json",
    "calibration.json",
    "calibration_by_closeness.json",
    "election_types.json",
    "election_winner_stats.json",
    "market_distribution.json",
    "partisan_bias_calibration.json",
    "partisan_bias_regression.json",
    "platform_comparison.json",
    "platform_stats.json",
    "prediction_vs_volume.json",
    "trader_accuracy_distribution.json",
    "trader_partisanship_actual_vs_perfect.json",
    "trader_partisanship_distribution.json",
    "volume_timeseries.json",
    "globe_elections.json",
    "globe_markets.json",
]


# ============================================================
# SNAPSHOT
# ============================================================

def snapshot(overwrite: bool = False):
    """Copy current JSON outputs to snapshot directory."""
    if SNAPSHOT_DIR.exists() and not overwrite:
        print(f"Snapshot already exists at {SNAPSHOT_DIR}")
        print("Use --snapshot --overwrite to replace it.")
        return

    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)

    copied = 0
    for fname in RESEARCH_TAB_FILES:
        src = WEB_DATA_DIR / fname
        if src.exists():
            shutil.copy2(src, SNAPSHOT_DIR / fname)
            copied += 1
        else:
            print(f"  SKIP {fname} (not found)")

    # Save metadata
    meta = {
        "timestamp": datetime.now().isoformat(),
        "files_copied": copied,
        "source_dir": str(WEB_DATA_DIR),
    }
    with open(SNAPSHOT_DIR / "_metadata.json", "w") as f:
        json.dump(meta, f, indent=2)

    print(f"Snapshot saved: {copied} files -> {SNAPSHOT_DIR}")


# ============================================================
# SCHEMA FINGERPRINTING
# ============================================================

def fingerprint(obj, path=""):
    """Recursively fingerprint a JSON object's structure."""
    info = {"type": type(obj).__name__}

    if isinstance(obj, dict):
        info["keys"] = sorted(obj.keys())
        info["children"] = {k: fingerprint(v, f"{path}.{k}") for k, v in obj.items()}
    elif isinstance(obj, list):
        info["length"] = len(obj)
        if obj:
            # Fingerprint first element as representative
            info["element_sample"] = fingerprint(obj[0], f"{path}[0]")
    elif isinstance(obj, (int, float)):
        if math.isnan(obj) or math.isinf(obj):
            info["anomaly"] = "NaN" if math.isnan(obj) else "Inf"
    elif obj is None:
        info["anomaly"] = "null"

    return info


def count_anomalies(obj, path=""):
    """Count NaN, Infinity, and null values in a JSON structure."""
    anomalies = []

    if isinstance(obj, dict):
        for k, v in obj.items():
            anomalies.extend(count_anomalies(v, f"{path}.{k}"))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            anomalies.extend(count_anomalies(v, f"{path}[{i}]"))
    elif isinstance(obj, float):
        if math.isnan(obj):
            anomalies.append(f"{path}: NaN")
        elif math.isinf(obj):
            anomalies.append(f"{path}: Infinity")
    elif obj is None:
        anomalies.append(f"{path}: null")

    return anomalies


# ============================================================
# REGRESSION CHECKS
# ============================================================

class CheckResult:
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"

    def __init__(self):
        self.results = []

    def add(self, level, file, message):
        self.results.append((level, file, message))

    def summary(self):
        fails = [r for r in self.results if r[0] == self.FAIL]
        warns = [r for r in self.results if r[0] == self.WARN]
        passes = [r for r in self.results if r[0] == self.PASS]
        return fails, warns, passes

    @property
    def worst(self):
        levels = {r[0] for r in self.results}
        if self.FAIL in levels:
            return self.FAIL
        if self.WARN in levels:
            return self.WARN
        return self.PASS


def check_schema_integrity(fname, baseline, current, results):
    """Check that top-level structure hasn't changed."""
    if isinstance(baseline, dict) and isinstance(current, dict):
        missing_keys = set(baseline.keys()) - set(current.keys())
        if missing_keys:
            results.add(CheckResult.FAIL, fname, f"Missing keys: {missing_keys}")
        else:
            results.add(CheckResult.PASS, fname, "All keys present")

        # Check array lengths
        for key in baseline:
            if key not in current:
                continue
            if isinstance(baseline[key], list) and isinstance(current[key], list):
                bl = len(baseline[key])
                cl = len(current[key])
                if bl > 0:
                    ratio = cl / bl
                    if ratio < 0.5 or ratio > 2.0:
                        results.add(CheckResult.FAIL, fname,
                                    f"Array '{key}' length changed drastically: {bl} → {cl}")
                    elif ratio < 0.8 or ratio > 1.2:
                        results.add(CheckResult.WARN, fname,
                                    f"Array '{key}' length shifted: {bl} → {cl} ({ratio:.1%})")

    elif isinstance(baseline, list) and isinstance(current, list):
        bl, cl = len(baseline), len(current)
        if bl > 0:
            ratio = cl / bl
            if ratio < 0.5 or ratio > 2.0:
                results.add(CheckResult.FAIL, fname,
                            f"Root array length changed drastically: {bl} → {cl}")


def check_anomalies(fname, baseline, current, results):
    """Check for new NaN/null/Infinity values."""
    baseline_anomalies = set(count_anomalies(baseline))
    current_anomalies = set(count_anomalies(current))
    new_anomalies = current_anomalies - baseline_anomalies

    if new_anomalies:
        sample = list(new_anomalies)[:5]
        results.add(CheckResult.FAIL, fname,
                    f"{len(new_anomalies)} new anomalies (NaN/null/Inf): {sample}")
    else:
        results.add(CheckResult.PASS, fname, "No new anomalies")


def check_aggregate_statistics(baseline, current, results):
    """Specific checks for aggregate_statistics.json."""
    fname = "aggregate_statistics.json"

    if not isinstance(baseline, dict) or not isinstance(current, dict):
        return

    # Total market count should be similar
    bl_total = sum(baseline.get("total_markets", []))
    cl_total = sum(current.get("total_markets", []))
    if bl_total > 0:
        ratio = cl_total / bl_total
        if ratio < 0.9 or ratio > 1.1:
            results.add(CheckResult.WARN, fname,
                        f"Total market count shifted: {bl_total:,} → {cl_total:,} ({ratio:.1%})")

    # No category with 0 markets that previously had >100
    bl_cats = dict(zip(baseline.get("categories", []), baseline.get("total_markets", [])))
    cl_cats = dict(zip(current.get("categories", []), current.get("total_markets", [])))
    for cat, count in bl_cats.items():
        if count > 100 and cl_cats.get(cat, -1) == 0:
            results.add(CheckResult.FAIL, fname,
                        f"Category '{cat}' dropped to 0 markets (was {count})")

    # Median volume check - the original bug
    medians = current.get("median_volume_k", [])
    markets = current.get("total_markets", [])
    cats = current.get("categories", [])
    for i, (cat, med, mkt) in enumerate(zip(cats, medians, markets)):
        if mkt > 500 and med == 0:
            results.add(CheckResult.WARN, fname,
                        f"Category '{cat}' has median=0 with {mkt} markets")


def check_brier_scores(fname, data, results):
    """Validate Brier scores are in [0, 1]."""
    def find_brier_values(obj, path=""):
        values = []
        if isinstance(obj, dict):
            for k, v in obj.items():
                if "brier" in k.lower() and isinstance(v, (int, float)):
                    values.append((f"{path}.{k}", v))
                else:
                    values.extend(find_brier_values(v, f"{path}.{k}"))
        elif isinstance(obj, list):
            for i, v in enumerate(obj):
                values.extend(find_brier_values(v, f"{path}[{i}]"))
        return values

    brier_vals = find_brier_values(data)
    out_of_range = [(p, v) for p, v in brier_vals if not (0 <= v <= 1)]
    if out_of_range:
        sample = out_of_range[:3]
        results.add(CheckResult.FAIL, fname,
                    f"{len(out_of_range)} Brier scores out of [0,1]: {sample}")
    elif brier_vals:
        results.add(CheckResult.PASS, fname,
                    f"{len(brier_vals)} Brier scores all in [0,1]")


def check_volumes(fname, data, results):
    """Validate volume values are non-negative."""
    def find_volume_values(obj, path=""):
        values = []
        if isinstance(obj, dict):
            for k, v in obj.items():
                if "volume" in k.lower() and isinstance(v, (int, float)):
                    values.append((f"{path}.{k}", v))
                elif "volume" in k.lower() and isinstance(v, list):
                    for i, item in enumerate(v):
                        if isinstance(item, (int, float)):
                            values.append((f"{path}.{k}[{i}]", item))
                else:
                    values.extend(find_volume_values(v, f"{path}.{k}"))
        elif isinstance(obj, list):
            for i, v in enumerate(obj):
                values.extend(find_volume_values(v, f"{path}[{i}]"))
        return values

    vol_vals = find_volume_values(data)
    negative = [(p, v) for p, v in vol_vals if v < 0]
    if negative:
        results.add(CheckResult.FAIL, fname,
                    f"{len(negative)} negative volume values: {negative[:3]}")


def check_category_distribution(fname, baseline, current, results):
    """For category-grouped files, check distribution sanity."""
    # Works for files that have a 'categories' key
    if not isinstance(current, dict) or "categories" not in current:
        return

    new_cats = set(current.get("categories", []))
    if not new_cats:
        results.add(CheckResult.FAIL, fname, "No categories found in output")
        return

    # Check no single category dominates (>50% of total would be suspicious)
    if "total_markets" in current:
        total = sum(current["total_markets"])
        if total > 0:
            for cat, count in zip(current["categories"], current["total_markets"]):
                if count / total > 0.5:
                    results.add(CheckResult.WARN, fname,
                                f"Category '{cat}' has {count/total:.0%} of all markets")


# ============================================================
# MAIN CHECK RUNNER
# ============================================================

def run_checks():
    """Run all regression checks against baseline snapshot."""
    if not SNAPSHOT_DIR.exists():
        print(f"No snapshot found at {SNAPSHOT_DIR}")
        print("Run with --snapshot first to create a baseline.")
        return 1

    results = CheckResult()
    files_checked = 0

    for fname in RESEARCH_TAB_FILES:
        baseline_path = SNAPSHOT_DIR / fname
        current_path = WEB_DATA_DIR / fname

        if not baseline_path.exists():
            continue  # File wasn't in baseline, skip

        if not current_path.exists():
            results.add(CheckResult.FAIL, fname, "File missing from current output")
            continue

        with open(baseline_path) as f:
            baseline = json.load(f)
        with open(current_path) as f:
            current = json.load(f)

        files_checked += 1

        # Universal checks
        check_schema_integrity(fname, baseline, current, results)
        check_anomalies(fname, baseline, current, results)

        # File-specific checks
        if fname == "aggregate_statistics.json":
            check_aggregate_statistics(baseline, current, results)

        if "brier" in fname:
            check_brier_scores(fname, current, results)

        if "volume" in fname or "aggregate" in fname or "summary" in fname:
            check_volumes(fname, current, results)

        if fname in ("aggregate_statistics.json", "market_distribution.json", "volume_timeseries.json"):
            check_category_distribution(fname, baseline, current, results)

    # Print report
    fails, warns, passes = results.summary()

    print(f"\n{'='*60}")
    print(f"REGRESSION TEST REPORT — {files_checked} files checked")
    print(f"{'='*60}")

    if fails:
        print(f"\n  FAILURES ({len(fails)}):")
        for level, fname, msg in fails:
            print(f"    FAIL  {fname}: {msg}")

    if warns:
        print(f"\n  WARNINGS ({len(warns)}):")
        for level, fname, msg in warns:
            print(f"    WARN  {fname}: {msg}")

    print(f"\n  SUMMARY: {len(passes)} pass, {len(warns)} warn, {len(fails)} fail")

    overall = results.worst
    print(f"\n  RESULT: {overall}")
    print(f"{'='*60}\n")

    return 1 if overall == CheckResult.FAIL else 0


# ============================================================
# ENTRY POINT
# ============================================================

def main():
    parser = argparse.ArgumentParser(description="Regression tests for web data JSON outputs")
    parser.add_argument("--snapshot", action="store_true",
                        help="Capture current JSON outputs as baseline")
    parser.add_argument("--check", action="store_true",
                        help="Run regression checks against baseline")
    parser.add_argument("--overwrite", action="store_true",
                        help="Overwrite existing snapshot (use with --snapshot)")
    args = parser.parse_args()

    if not args.snapshot and not args.check:
        parser.print_help()
        return 1

    if args.snapshot:
        snapshot(overwrite=args.overwrite)
        return 0

    if args.check:
        return run_checks()


if __name__ == "__main__":
    sys.exit(main())
